spring.application.name=enterprise-ai-agent
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_ai
spring.datasource.username=postgres
spring.datasource.password=Mahadev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true